### ISSUE TITLE
API key and Source missing

### ISSUE THREAD

**Issue by DaxeshV** [DawnImpulse/kowts-android#1]
Where I found the API key and API URL. it is missing in the project.

**Comment by DawnImpulse** [comment]
Hii Daxesh, Thanks for taking interest in Kowts API. The quotes backend is my own API service & to use it you need to take permission from me. So I would like to know what is your use-case for the same & are you going to use it in a project for monetization purpose. RegardsSakshamFrom: Daxesh VekariyaSent: Wednesday, December 11, 2019 11:44 PMTo: DawnImpulse/kowts-androidCc: SubscribedSubject: [DawnImpulse/kowts-android] API key and Source missing (#1) Where I found the API key and API URL. it is missing in the project.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by DawnImpulse** [comment]
Hii Daxesh, Thanks for taking interest in Kowts API. The Kowts backend is my own API service & to use it you need to take permission from me. So I would like to know what is your use-case for the same & are you going to use it in a project for monetization purposes. Let's communicate regarding the same on either twitter @DawnImpulse  or on my email dawnimpulse@gmail.com.

**Comment by DaxeshV** [comment]
ok @DawnImpulse thank you for the update.
